# Generated by Django 4.2.2 on 2023-06-27 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم الهاتف')),
                ('instagram_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='رابط الانستغرام')),
                ('facebook_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='رابط الفيسبوك')),
                ('twitter_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='رابط التويتر')),
                ('snapchat_link', models.CharField(blank=True, max_length=100, null=True, verbose_name='رابط السناب شات')),
                ('state', models.BooleanField(default=True, verbose_name='فعالة')),
            ],
            options={
                'verbose_name': 'عن الشركة',
                'verbose_name_plural': 'عن الشركة',
            },
        ),
        migrations.CreateModel(
            name='ServiceCities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='المدينة')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'المدينة',
                'verbose_name_plural': 'المدن',
            },
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'القسم', 'verbose_name_plural': 'الأقسام'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'الخدمة', 'verbose_name_plural': 'الخدمات'},
        ),
        migrations.AlterModelOptions(
            name='subcategories',
            options={'verbose_name': 'القسم الفرعي', 'verbose_name_plural': 'الأقسام الفرعية'},
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='post', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subcategories', verbose_name='القسم الفرعي'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100, unique=True, verbose_name='عنوان الخدمة'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categories', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='القسم الفرعي'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='الرابط'),
        ),
    ]
