# Generated by Django 4.2.2 on 2023-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_about_servicecities_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecities',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
