# Generated by Django 4.2.2 on 2023-06-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servicecities_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='الرابط'),
        ),
        migrations.AlterField(
            model_name='subcategories',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='الرابط'),
        ),
    ]
