# Generated by Django 4.2.2 on 2023-06-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_categories_slug_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='telephone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='التليفون'),
        ),
    ]
