# Generated by Django 4.2.2 on 2023-06-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_about_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=models.TextField(default=1, verbose_name='الوصف'),
            preserve_default=False,
        ),
    ]
