# Generated by Django 4.2.2 on 2023-06-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categories_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequentlyQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='السؤال')),
                ('content', models.TextField(verbose_name='الإجابة')),
            ],
            options={
                'verbose_name': 'الأسئلة الشائعة',
                'verbose_name_plural': 'الأسئلة الشائعة',
            },
        ),
    ]
