# Generated by Django 4.2.2 on 2023-06-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_frequentlyquestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email_link',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='البريد الإلكتروني'),
        ),
    ]
