# Generated by Django 4.2.2 on 2023-06-28 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_about_email_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecities', verbose_name='المدينة')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'الخدمة في المدينة',
                'verbose_name_plural': 'الخدمات في المدن',
            },
        ),
    ]
