# Generated by Django 4.2.2 on 2023-08-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_post_content_postpictures'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postpictures',
            options={'verbose_name': 'صور الخدمة', 'verbose_name_plural': 'صور الخدمات'},
        ),
    ]
